spring.main.banner-mode: console

# DB Connection Setting
spring.datasource.url: jdbc:oracle:thin:@xxxx:1521/PDB1.gse00010236.oraclecloud.internal
spring.datasource.username: mit-ai
spring.datasource.password: mitai
spring.datasource.driver-class-name: oracle.jdbc.OracleDriver

server.port: 8585

spring.thymeleaf.cache: false
spring.thymeleaf.prefix: classpath:/templates/

