package com.mitsubishi.demo.common.mapper;

import com.mitsubishi.demo.common.dataset.InformationTable;
import com.mitsubishi.demo.common.dataset.InformationTableExample;
import com.mitsubishi.demo.common.dataset.InformationTableKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InformationTableMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INFORMATION_TABLE
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	long countByExample(InformationTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INFORMATION_TABLE
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int deleteByExample(InformationTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INFORMATION_TABLE
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int deleteByPrimaryKey(InformationTableKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INFORMATION_TABLE
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int insert(InformationTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INFORMATION_TABLE
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int insertSelective(InformationTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INFORMATION_TABLE
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	List<InformationTable> selectByExample(InformationTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INFORMATION_TABLE
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	InformationTable selectByPrimaryKey(InformationTableKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INFORMATION_TABLE
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int updateByExampleSelective(@Param("record") InformationTable record,
			@Param("example") InformationTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INFORMATION_TABLE
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int updateByExample(@Param("record") InformationTable record, @Param("example") InformationTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INFORMATION_TABLE
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int updateByPrimaryKeySelective(InformationTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INFORMATION_TABLE
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int updateByPrimaryKey(InformationTable record);
}