package com.mitsubishi.demo.common.mapper;

import com.mitsubishi.demo.common.dataset.PersonCareerData;
import com.mitsubishi.demo.common.dataset.PersonCareerDataExample;
import com.mitsubishi.demo.common.dataset.PersonCareerDataKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonCareerDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON_CAREER_DATA
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	long countByExample(PersonCareerDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON_CAREER_DATA
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int deleteByExample(PersonCareerDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON_CAREER_DATA
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int deleteByPrimaryKey(PersonCareerDataKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON_CAREER_DATA
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int insert(PersonCareerData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON_CAREER_DATA
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int insertSelective(PersonCareerData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON_CAREER_DATA
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	List<PersonCareerData> selectByExample(PersonCareerDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON_CAREER_DATA
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	PersonCareerData selectByPrimaryKey(PersonCareerDataKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON_CAREER_DATA
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PersonCareerData record,
			@Param("example") PersonCareerDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON_CAREER_DATA
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int updateByExample(@Param("record") PersonCareerData record, @Param("example") PersonCareerDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON_CAREER_DATA
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int updateByPrimaryKeySelective(PersonCareerData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON_CAREER_DATA
	 * @mbg.generated  Tue Oct 17 17:31:01 CST 2017
	 */
	int updateByPrimaryKey(PersonCareerData record);
}