package com.mitsubishi.demo.common.mapper;

import com.mitsubishi.demo.common.dataset.PersonTable;
import com.mitsubishi.demo.common.dataset.PersonTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonTableMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PERSON_TABLE
	 * 
	 * @mbg.generated Tue Oct 17 15:14:57 CST 2017
	 */
	long countByExample(PersonTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PERSON_TABLE
	 * 
	 * @mbg.generated Tue Oct 17 15:14:57 CST 2017
	 */
	int deleteByExample(PersonTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PERSON_TABLE
	 * 
	 * @mbg.generated Tue Oct 17 15:14:57 CST 2017
	 */
	int deleteByPrimaryKey(String personNum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PERSON_TABLE
	 * 
	 * @mbg.generated Tue Oct 17 15:14:57 CST 2017
	 */
	int insert(PersonTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PERSON_TABLE
	 * 
	 * @mbg.generated Tue Oct 17 15:14:57 CST 2017
	 */
	int insertSelective(PersonTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PERSON_TABLE
	 * 
	 * @mbg.generated Tue Oct 17 15:14:57 CST 2017
	 */
	List<PersonTable> selectByExample(PersonTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PERSON_TABLE
	 * 
	 * @mbg.generated Tue Oct 17 15:14:57 CST 2017
	 */
	PersonTable selectByPrimaryKey(String personNum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PERSON_TABLE
	 * 
	 * @mbg.generated Tue Oct 17 15:14:57 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PersonTable record, @Param("example") PersonTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PERSON_TABLE
	 * 
	 * @mbg.generated Tue Oct 17 15:14:57 CST 2017
	 */
	int updateByExample(@Param("record") PersonTable record, @Param("example") PersonTableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PERSON_TABLE
	 * 
	 * @mbg.generated Tue Oct 17 15:14:57 CST 2017
	 */
	int updateByPrimaryKeySelective(PersonTable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PERSON_TABLE
	 * 
	 * @mbg.generated Tue Oct 17 15:14:57 CST 2017
	 */
	int updateByPrimaryKey(PersonTable record);
}