package com.mitsubishi.demo.common.service;

import com.mitsubishi.demo.common.dataset.PersonJobHistoryTable;
import com.mitsubishi.demo.common.dataset.PersonJobHistoryTableExample;
import com.mitsubishi.demo.common.dataset.PersonJobHistoryTableKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonJobHistoryTableService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON_JOB_HISTORY_TABLE
     *
     * @mbg.generated Tue Oct 17 17:13:29 CST 2017
     */
    long countByExample(PersonJobHistoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON_JOB_HISTORY_TABLE
     *
     * @mbg.generated Tue Oct 17 17:13:29 CST 2017
     */
    int deleteByExample(PersonJobHistoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON_JOB_HISTORY_TABLE
     *
     * @mbg.generated Tue Oct 17 17:13:29 CST 2017
     */
    int deleteByPrimaryKey(PersonJobHistoryTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON_JOB_HISTORY_TABLE
     *
     * @mbg.generated Tue Oct 17 17:13:29 CST 2017
     */
    int insert(PersonJobHistoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON_JOB_HISTORY_TABLE
     *
     * @mbg.generated Tue Oct 17 17:13:29 CST 2017
     */
    int insertSelective(PersonJobHistoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON_JOB_HISTORY_TABLE
     *
     * @mbg.generated Tue Oct 17 17:13:29 CST 2017
     */
    List<PersonJobHistoryTable> selectByExample(PersonJobHistoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON_JOB_HISTORY_TABLE
     *
     * @mbg.generated Tue Oct 17 17:13:29 CST 2017
     */
    PersonJobHistoryTable selectByPrimaryKey(PersonJobHistoryTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON_JOB_HISTORY_TABLE
     *
     * @mbg.generated Tue Oct 17 17:13:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") PersonJobHistoryTable record, @Param("example") PersonJobHistoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON_JOB_HISTORY_TABLE
     *
     * @mbg.generated Tue Oct 17 17:13:29 CST 2017
     */
    int updateByExample(@Param("record") PersonJobHistoryTable record, @Param("example") PersonJobHistoryTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON_JOB_HISTORY_TABLE
     *
     * @mbg.generated Tue Oct 17 17:13:29 CST 2017
     */
    int updateByPrimaryKeySelective(PersonJobHistoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON_JOB_HISTORY_TABLE
     *
     * @mbg.generated Tue Oct 17 17:13:29 CST 2017
     */
    int updateByPrimaryKey(PersonJobHistoryTable record);
}